### PR TITLE
Replace dot-like characters in campaign url mapping

### PR DESCRIPTION
**Pull request by jivinivan**

### CODE REVIEW

**Comment by sarahspang** [comment]
@sperand-io -- any blockers to getting this merged? this is the fix for the settings bug in the ambassador integration!

**Comment by sperand-io** [comment]
hey @jivinivan sorry for the delay on this. can you help us clarify why (and which) customers are dropping those characters in our UI in the first place? 

my original understanding, which caused the slower pace of resolution here, was that this was an issue with our app serializing certain character sequences into these unicode chars automatically upon saving settings. However, it appears that certain customers are pasting the unicode `full-stop full-width` character into the field directly. Is that how they're rendered in your UI (which they'd copy and paste)?

If so, we'd propose you change it to regular characters on your side, and then we'll be happy to run a migration on all of the settings to change any w/ the unicode char to the proper characters.

For any cases that require immediate mitigation, is there any reason we can't ask users to go in and make those edits in the settings sheets themselves?

LMK your thoughts!

**Comment by jivinivan** [comment]
@sperand-io is there a problem with the Segment UI? I'm getting a blank screen and console error.  
image

**Comment by thehydroimpulse** [comment]
@jivinivan We're working on getting it back up.

**Comment by thehydroimpulse** [comment]
@jivinivan app should be back up.

**Comment by jivinivan** [comment]
@sperand-io the characters still get added when I clear the field and type each character.

**Comment by chaselee** [comment]
@sperand-io might it be easiest to merge this until we know why the Segment admin uses these characters?

**Comment by chaselee** [comment]
@sarahspang @sperand-io @thehydroimpulse can we merge this?

**Comment by sarahspang** [comment]
Hey Chase, Chris is investigating and will follow up here. Apologies again for the delays!




--- original message ---
On Tue, Nov 1, 2016 at 01:05 pm, <notifications@github.com> Chase Lee wrote:

@sarahspang @sperand-io @thehydroimpulse can we merge this?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
--- end of original message ---

**Comment by chaselee** [comment]
Thanks @sarahspang. @sperand-io let us know if we can help with your investigation. This is essentially a one line change `url = url.replace(/．/g, '.');`. Given how that settings field is used I see no downside to adopting this line. Certainly safer than you trying to change your admin, and once you do change your admin, this line will have no effect and can be removed at any point.

**Comment by sperand-io** [comment]
We can't seem to reproduce the problem @jivinivan noted above (that the admin UI is automatically replacing dots with the unicode variant you're noting here) with chrome on our macs. Eg. see here: 

screen shot 2016-11-01 at 2 01 50 pm

If you can send us a screenshot or video with info about your (or your customers') browsing env... that would be super helpful to help us isolate this app bug. 

In the meantime, we'll get this out as a stopgap.

**Comment by chaselee** [comment]
Thanks @sperand-io. We're using Chrome on Macs as well. We'll take a look and send over what we're seeing, but thanks for getting this out in the meantime!

**Comment by jivinivan** [comment]
@sperand-io the problem is in the generated script. The value seems to save fine in the admin but the dot characters are different in the generated analytics.min.js. See here http://cdn.segment.com/analytics.js/v1/5cuXV7wyjv/analytics.min.js

Specifically the `"campaigns":{"example．getambassador．com/*":"260","example．com/checkout":"222"}` section.

**Pull request merged**
